# Generated by Django 4.2.6 on 2023-12-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0003_remove_alimento_valor_energetico_alimento_calorias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('calorias_consumidas', models.IntegerField(default=0)),
                ('alimentos', models.ManyToManyField(to='alimento.alimento')),
            ],
        ),
    ]
