# Generated by Django 4.2.6 on 2023-12-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_data_criacao'),
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='paciente',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
            preserve_default=False,
        ),
    ]
