# Generated by Django 4.2.6 on 2023-12-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_alter_diario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
