# Generated by Django 4.2.6 on 2023-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieta', '0004_refeicao_alimentos_delete_alimentorefeicao'),
        ('diario', '0007_alter_diario_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diario',
            name='refeicoes_do_dia',
        ),
        migrations.AddField(
            model_name='diario',
            name='refeicoes',
            field=models.ManyToManyField(related_name='diarios', to='dieta.refeicao'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='data',
            field=models.DateTimeField(editable=False),
        ),
    ]
