# Generated by Django 4.2.6 on 2023-12-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_rename_contato_paciente_whatsapp_and_more'),
        ('diario', '0009_alter_diario_refeicoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
