# Generated by Django 4.2.6 on 2023-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=11)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cpf', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=20)),
                ('diagnostico', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Aguardando formulário pós consulta'), (2, 'Aguardando formulário pré consulta'), (3, 'Dieta em andamento'), (4, 'Dieta concluída')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
