# Generated by Django 4.2.6 on 2023-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='objetivo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
