# Generated by Django 4.2.6 on 2023-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_paciente_descricao_alter_paciente_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Aguardando formulário pós consulta'), (2, 'Aguardando formulário pré consulta'), (3, 'Dieta em andamento'), (4, 'Dieta concluída')], default=1),
        ),
    ]
