# Generated by Django 4.2.6 on 2023-12-10 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_alter_paciente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
