# Generated by Django 4.2.6 on 2023-12-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0004_paciente_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='contato',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='senha',
        ),
    ]
