# Generated by Django 4.2.6 on 2023-12-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0007_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
