# Generated by Django 4.2.6 on 2023-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_paciente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
