# Generated by Django 4.2.6 on 2023-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(blank=True, max_length=30)),
                ('contato', models.CharField(max_length=11)),
                ('crn', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
