# Generated by Django 4.2.6 on 2023-12-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.IntegerField()),
                ('id_pergunta', models.IntegerField()),
            ],
        ),
    ]
