# Generated by Django 4.2.6 on 2023-12-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('id_opcao', models.IntegerField()),
                ('substituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento')),
            ],
        ),
    ]
