# Generated by Django 4.2.6 on 2023-12-11 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refeicao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opcao',
        ),
    ]
