# Generated by Django 4.2.6 on 2023-12-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0003_remove_alimento_valor_energetico_alimento_calorias_and_more'),
        ('dieta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='numero_de_refeicoes',
        ),
        migrations.AddField(
            model_name='dieta',
            name='nome',
            field=models.CharField(default='Nova dieta', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dieta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='pendente', max_length=50),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='dieta.dieta')),
            ],
        ),
        migrations.CreateModel(
            name='AlimentoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieta.refeicao')),
            ],
        ),
    ]
