# Generated by Django 4.2.6 on 2023-12-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_data_criacao'),
        ('dieta', '0002_remove_dieta_numero_de_refeicoes_dieta_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(related_name='dietas', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='andamento', max_length=50),
        ),
    ]
