# Generated by Django 4.2.6 on 2023-12-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_paciente_usuario'),
        ('dieta', '0004_refeicao_alimentos_delete_alimentorefeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='paciente',
            field=models.ManyToManyField(blank=True, related_name='dietas', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='dieta',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='dieta.dieta'),
        ),
    ]
