# Generated by Django 4.2.6 on 2023-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('pre', 'Pré-consulta'), ('pos', 'Pós-consulta')], max_length=3),
        ),
    ]
