# Generated by Django 4.2.6 on 2023-12-22 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='pergunta',
            old_name='obrigatorio',
            new_name='e_obrigatoria',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='formulario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formulario.formulario'),
            preserve_default=False,
        ),
    ]
