# Generated by Django 4.2.6 on 2023-12-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_formulario_rename_obrigatorio_pergunta_e_obrigatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='nome',
            field=models.CharField(default='nova pergunta', max_length=255),
            preserve_default=False,
        ),
    ]
