# Generated by Django 4.2.6 on 2023-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_pergunta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('pre-consulta', 'Pré-consulta'), ('pos-consulta', 'Pós-consulta')], default='pre-consulta', max_length=15),
        ),
    ]
