# Generated by Django 4.2.6 on 2023-11-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('porcao', models.DecimalField(decimal_places=6, max_digits=6)),
                ('valor_energetico', models.DecimalField(decimal_places=6, max_digits=6)),
                ('fibra_alimentar', models.DecimalField(decimal_places=6, max_digits=6)),
                ('carboidratos', models.DecimalField(decimal_places=6, max_digits=6)),
                ('proteinas', models.DecimalField(decimal_places=6, max_digits=6)),
                ('gorduras', models.DecimalField(decimal_places=6, max_digits=6)),
                ('e_substituto', models.BooleanField(default=False)),
            ],
        ),
    ]
