# Generated by Django 4.2.6 on 2023-11-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='fibra_alimentar',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='gorduras',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='porcao',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='valor_energetico',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
