# Generated by Django 4.2.6 on 2023-12-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0002_alter_alimento_carboidratos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='valor_energetico',
        ),
        migrations.AddField(
            model_name='alimento',
            name='calorias',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='tipo',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
