# Generated by Django 4.2.6 on 2023-12-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0003_remove_alimento_valor_energetico_alimento_calorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='consumido',
            field=models.BooleanField(default=False),
        ),
    ]
