# Generated by Django 4.2.6 on 2023-12-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0004_alimento_consumido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='consumido',
        ),
    ]
